### ISSUE TITLE
HRM > Recruitment

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#21578]
Fixing up the recruitment module for `17.0` to get out of alpha status.

## Bugs:

- [ ] Recruitment Module : warning #20470
- [x] broken email field `appplication` (fixed #21563)
- [x] numbering `jobs` (fixed #21563)
- [ ] broken establishment field (SEE:  #20464)
- [x] wrong odf output path -- wrong output dir in odt file generation for recruitment #19449
- [ ] Bug Recruitment Modul ... referrer false #18488
- [ ] API endpoints broken
- [ ] Application > Rating not existing
- [ ] Actions are not being recorded
- [ ] add to GDPR deletion schedule
- [ ] enable to set `fk_user_recruiter` on position create form (defaults feature)

## Features:
- [x] advanced numbering `application` (fixed #21563)

## Cleanup (naming):

**Comment by cfoellmann** [comment]
will have a look at #18434

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/21695

**Comment by cfoellmann** [comment]
@eldy is using `xyz_card.php` on the top level of modules a hard must now?
for me it seems "more elegant" like this
`recruitment/application/card.php`
`recruitment/application/list.php`
`recruitment/job/card.php`
`recruitment/job/list.php`

**Comment by cfoellmann** [comment]
@eldy how do I need to change the `status` field in the class RecruitmentCandidature to "just" not show it on creation card?
Setting a different status than draft has negative consequences.

**Comment by eldy** [comment]
Yes 
mymodule/myobject/file  is more elegant. But we try to increase the use and compatibility with module builder and 
mymodule/myobject_file   is easier (at least currently) to manage in our low-code / no-code point of view. I don't want to break this before a long time, the modulebuilder needs more stabilisation to be done before doing refactoring.
