### ISSUE TITLE
[UI/UX] Update body class to all pages

### ISSUE THREAD

**Issue by john-botella** [Dolibarr/dolibarr#26856]
### Feature Request

Here is a summary of the actions to be taken on Dolibarr pages following the ui/ux round table at the Dolibarr winter 2023 dev camp. 

To help css integrator to easily target elements according to page context.

Note : css class name use bem write style
 

### Suggested implementation

For all page add css classes to body

1. To describe curent module use the prefix **mod-** followed by the module name ex : **mod-**_modulename_
2. To describe curent page type  use the prefix **page-** followed by the page type: **page-**list
   list of page type : page-list, page-card, page-dashboard, page-stats, page-admin, page-card_documents , page-card_notes, page-card_agenda
   
3. Differentiate between edit, create, and delete  at file level by using css class.
    To describe curent page action use the prefix **action-** followed by the curent action.
    limit class to **action-create, action-delete, action-update**
    Action-view isn't present because irrelevant view is default action

 ### Suggested steps for 3   
- [ ] add behavior to llxHeader

### Suggested steps for 1 & 2 

- [x] **Module Holiday** #30375
- [x] ./holiday/card.php
- [x] ./holiday/card_group.php
- [x] ./holiday/define_holiday.php
- [x] ./holiday/document.php
- [x] ./holiday/info.php
- [x] ./holiday/list.php
- [x] ./holiday/month_report.php
- [x] ./holiday/view_log.php

- [x] **Module loan** #30370
- [x] ./loan/card.php #30370
- [x] ./loan/document.php #30370
- [x] ./loan/info.php #30370
- [x] ./loan/list.php #30370
- [x] ./loan/note.php #30370
- [x] ./loan/payment/card.php #30370
- [x] ./loan/payment/payment.php #30370
- [x] ./loan/schedule.php #30370

- [ ] **Module asset**
- [x] ./asset/accountancy_codes.php #27152
- [ ] ./asset/admin/asset_extrafields.php
- [ ] ./asset/admin/assetmodel_extrafields.php
- [ ] ./asset/admin/setup.php
- [x] ./asset/agenda.php #27152
- [x] ./asset/card.php #27152
- [x] ./asset/depreciation_options.php #27152
- [x] ./asset/depreciation.php #27152
- [x] ./asset/disposal.php #27152
- [x] ./asset/document.php #27152
- [x] ./asset/list.php #27152
- [x] ./asset/model/accountancy_codes.php #27152
- [x] ./asset/model/agenda.php #27152
- [x] ./asset/model/card.php #27152
- [x] ./asset/model/depreciation_options.php #27152
- [x] ./asset/model/list.php #27152
- [x] ./asset/model/note.php #27152
- [x] ./asset/note.php #27152

- [ ] **Module barcode**
- [ ] ./barcode/codeinit.php
- [ ] ./barcode/printsheet.php
- [ ] ./blockedlog/admin/blockedlog_list.php
- [ ] ./blockedlog/admin/blockedlog.php
- [ ] **Module command**

- [x] ./commande/agenda.php #27144
- [x] ./commande/card.php #27144
- [x] ./commande/contact.php #27144
- [ ] ./commande/customer.php
- [x] ./commande/document.php #27144
- [ ] ./commande/index.php
- [ ] ./commande/list_det.php
- [ ] ./commande/list_det.php
- [x] ./commande/list.php #27144
- [x] ./commande/note.php #27144
- [x] ./commande/stats/index.php #27144
- [ ] ./delivery/card.php

- [x] **Module don** #27153
- [x] ./don/admin/donation_extrafields.php #27153
- [x] ./don/admin/donation.php #27153
- [x] ./don/card.php #27153
- [x] ./don/document.php #27153
- [x] ./don/index.php #27153
- [x] ./don/info.php #27153
- [x] ./don/list.php #27153
- [x] ./don/note.php #27153
- [x] ./don/payment/card.php #27153
- [x] ./don/payment/payment.php #27153
- [x] ./don/stats/index.php #27153

- [ ] **Module export**
- [ ] ./exports/export.php
- [ ] ./exports/index.php

- [ ] **Module knowledgemanagement**
- [ ] ./knowledgemanagement/knowledgemanagementindex.php #29867
- [ ] ./knowledgemanagement/knowledgerecord_agenda.php #29867
- [ ] ./knowledgemanagement/knowledgerecord_card.php #29867
- [ ] ./knowledgemanagement/knowledgerecord_contact.php #29867
- [ ] ./knowledgemanagement/knowledgerecord_document.php #29867
- [ ] ./knowledgemanagement/knowledgerecord_list.php #29867
- [ ] ./knowledgemanagement/knowledgerecord_note.php #29867

- [x] **Module partnership** #29875
- [x] ./partnership/admin/partnership_extrafields.php #29875
- [x] ./partnership/admin/setup.php #29875
- [x] ./partnership/admin/website.php #29875
- [x] ./partnership/partnership_agenda.php #29875
- [x] ./partnership/partnership_card.php #29875
- [x] ./partnership/partnership_contact.php #29875
- [x] ./partnership/partnership_document.php #29875
- [x] ./partnership/partnership_list.php #29875
- [x] ./partnership/partnership_note.php #29875

- [ ] **./paypal/admin/paypal.php**

- [ ] **Module product**
- [x] ./product/admin/dynamic_prices.php
- [x] ./product/admin/inventory_extrafields.php
- [x] ./product/admin/price_rules.php
- [x] ./product/admin/product_extrafields.php
- [x] ./product/admin/product_lot_extrafields.php
- [x] ./product/admin/product_lot.php
- [x] ./product/admin/product_supplier_extrafields.php
- [x] ./product/admin/product_tools.php
- [x] ./product/admin/product.php
- [x] ./product/admin/stock_extrafields.php
- [x] ./product/admin/stock_mouvement_extrafields.php
- [x] ./product/agenda.php
- [x] ./product/card.php
- [x] ./product/composition/card.php
- [x] ./product/document.php
- [x] ./product/dynamic_price/editor.php
- [ ] ./product/fournisseurs.php
- [ ] ./product/index.php
- [x] ./product/inventory/card.php
- [x] ./product/inventory/inventory.php
- [ ] ./product/inventory/list.php
- [ ] ./product/list.php
- [ ] ./product/list.php
- [ ] ./product/note.php
- [ ] ./product/popuprop.php
- [ ] ./product/price.php
- [ ] ./product/reassort.php
- [ ] ./product/reassortlot.php
- [ ] ./product/stats/bom.php
- [x] ./product/stats/card.php #29894
- [x] ./product/stats/card.php #29894
- [x] ./product/stats/commande_fournisseur.php #29894
- [x] ./product/stats/commande.php #29894
- [x] ./product/stats/contrat.php #29894
- [x] ./product/stats/facture_fournisseur.php #29894
- [x] ./product/stats/facture.php #29894
- [x] ./product/stats/facturerec.php #29894
- [x] ./product/stats/mo.php #29894
- [x] ./product/stats/propal.php #29894
- [x] ./product/stats/supplier_proposal.php #29894
- [ ] ./product/stock/card.php
- [x] ./product/stock/fiche-valo.php #29894
- [x] ./product/stock/index.php #29894
- [x] ./product/stock/info.php #29894
- [x] ./product/stock/list.php #29894
- [x] ./product/stock/massstockmove.php #29894
- [x] ./product/stock/movement_card.php #29894
- [x] ./product/stock/movement_list.php #29894
- [x] ./product/stock/product.php #29894
- [x] ./product/stock/productlot_card.php #29894
- [x] ./product/stock/productlot_document.php #29894
- [x] ./product/stock/productlot_list.php #29894
- [x] ./product/stock/productlot_note.php #29894
- [x] ./product/stock/replenish.php #29894
- [x] ./product/stock/replenishorders.php #29894
- [x] ./product/stock/stats/commande_fournisseur.php
- [x] ./product/stock/stats/expedition.php
- [ ] ./product/stock/stats/mo.php
- [x] ./product/stock/stats/reception.php #29894
- [x] ./product/stock/stockatdate.php #29894
- [x] ./product/stock/stocktransfer/stocktransfer_agenda.php
- [x] ./product/stock/stocktransfer/stocktransfer_card.php
- [ ] ./product/stock/stocktransfer/stocktransfer_contact.php
- [x] ./product/stock/stocktransfer/stocktransfer_document.php
- [x] ./product/stock/stocktransfer/stocktransfer_list.php
- [x] ./product/stock/stocktransfer/stocktransfer_note.php
- [x] ./product/stock/valo.php #29894
- [ ] ./product/traduction.php

- [ ] **Module resource**
- [ ] ./resource/agenda.php
- [ ] ./resource/card.php
- [ ] ./resource/contact.php
- [ ] ./resource/document.php
- [ ] ./resource/element_resource.php
- [ ] ./resource/list.php
- [ ] ./resource/note.php

- [ ] **Module supplier_proposal**
- [ ] ./supplier_proposal/admin/supplier_proposal_extrafields.php
- [ ] ./supplier_proposal/admin/supplier_proposaldet_extrafields.php
- [ ] ./supplier_proposal/card.php
- [ ] ./supplier_proposal/contact.php
- [ ] ./supplier_proposal/document.php
- [ ] ./supplier_proposal/index.php
- [ ] ./supplier_proposal/info.php
- [ ] ./supplier_proposal/list.php
- [ ] ./supplier_proposal/note.php

- [ ] **Module takepos**
- [ ] ./takepos/admin/appearance.php
- [ ] ./takepos/admin/bar.php
- [ ] ./takepos/admin/orderprinters.php
- [ ] ./takepos/admin/other.php
- [ ] ./takepos/admin/receipt.php
- [ ] ./takepos/admin/setup.php
- [ ] ./takepos/admin/terminal.php
- [ ] ./takepos/invoice.php
- [ ] ./takepos/phone.php

- [ ] **Module ticket**
- [ ] ./ticket/agenda.php
- [ ] ./ticket/card.php
- [ ] ./ticket/contact.php
- [ ] ./ticket/document.php
- [ ] ./ticket/index.php
- [ ] ./ticket/list.php
- [ ] ./ticket/messaging.php
- [ ] ./ticket/stats/index.php

- [ ] **Module user**
- [x] ./user/admin/group_extrafields.php
- [x] ./user/admin/user_extrafields.php
- [x] ./user/agenda_extsites.php
- [x] ./user/bank.php
- [x] ./user/card.php
- [x] ./user/clicktodial.php
- [x] ./user/document.php
- [x] ./user/group/card.php
- [x] ./user/group/ldap.php
- [x] ./user/group/list.php
- [x] ./user/group/perms.php
- [x] ./user/hierarchy.php
- [x] ./user/home.php
- [ ] ./user/info.php
- [x] ./user/ldap.php
- [x] ./user/list.php
- [x] ./user/note.php
- [x] ./user/notify/card.php
- [x] ./user/param_ihm.php
- [x] ./user/perms.php
- [x] ./user/virtualcard.php

- [ ] **Module webhook**
- [ ] ./webhook/target_card.php
- [ ] ./webhook/target_list.php
- [ ] ./webhook/webhookindex.php

- [ ] **Module website**
- [ ] ./website/index.php
- [ ] ./website/websiteaccount_card.php
- [ ] **Module workstation**
- [ ] ./workstation/workstation_agenda.php
- [ ] ./workstation/workstation_card.php
- [ ] ./workstation/workstation_document.php
- [ ] ./workstation/workstation_list.php
- [ ] ./workstation/workstation_note.php
- [ ] ./categories/traduction.php
- [ ] ./index.php

- [ ] **Module fichinter**
- [ ] ./fichinter/contact.php
- [ ] ./fichinter/index.php
- [ ] ./fichinter/card-rec.php
- [ ] ./fichinter/note.php
- [ ] ./fichinter/document.php
- [ ] ./fichinter/stats/index.php
- [ ] ./fichinter/admin/fichinterdet_extrafields.php
- [ ] ./fichinter/admin/fichinter_extrafields.php
- [ ] ./fichinter/agenda.php
- [ ] ./fichinter/list.php
- [ ] ./fichinter/card.php

- [x] **Module fourn_commande**
- [x] ./fourn/commande/info.php #27381
- [x] ./fourn/commande/contact.php #27381
- [x] ./fourn/commande/index.php #27381
- [x] ./fourn/commande/note.php #27381
- [x] ./fourn/commande/document.php #27381
- [x] ./fourn/commande/dispatch.php #27381
- [x] ./fourn/commande/list.php #27381
- [x] ./fourn/commande/card.php #27381

- [ ] **Module fourn_product**
- [ ] ./fourn/product/list.php
- [ ] **Module fourn_facture**
- [ ] ./fourn/facture/info.php
- [ ] ./fourn/facture/contact.php
- [ ] ./fourn/facture/index.php
- [ ] ./fourn/facture/rapport.php
- [ ] ./fourn/facture/card-rec.php
- [ ] ./fourn/facture/note.php
- [ ] ./fourn/facture/document.php
- [ ] ./fourn/facture/list-rec.php
- [ ] ./fourn/facture/list.php
- [ ] ./fourn/facture/card.php
- [ ] ./fourn/facture/paiement.php
- [ ] ./fourn/card.php
- [ ] ./fourn/recap-fourn.php

- [x] **Module accountancy**
- [x] ./accountancy/customer/lines.php
- [x] ./accountancy/supplier/index.php
- [x] ./accountancy/supplier/list.php
- [x] ./accountancy/supplier/card.php
- [x] ./accountancy/supplier/lines.php
- [x] ./accountancy/expensereport/index.php
- [x] ./accountancy/expensereport/list.php
- [x] ./accountancy/expensereport/card.php
- [x] ./accountancy/expensereport/lines.php
- [x] accountancy/journal/bankjournal.php #30026
- [x] accountancy/journal/expensereportsjournal.php #30026
- [x] accountancy/journal/purchasesjournal.php #30026
- [x] accountancy/journal/sellsjournal.php #30026
- [x] accountancy/journal/variousjournal.php #30026
- [x] bookkeeping/balance.php #30028
- [x] accountancy/bookkeeping/card.php #30028
- [x] accountancy/bookkeeping/export.php #30028
- [x] accountancy/bookkeeping/list.php #30028
- [x] accountancy/bookkeeping/listbyaccount.php #30028

 
 

- [ ] **Module margin**
- [ ] ./margin/tabs/thirdpartyMargins.php
- [ ] ./margin/tabs/productMargins.php
- [ ] ./margin/agentMargins.php
- [ ] ./margin/checkMargins.php
- [ ] ./margin/admin/margin.php
- [ ] ./margin/customerMargins.php
- [ ] ./margin/productMargins.php

- [x] **Module projet**
- [x] ./projet/element.php #30357
- [x] ./projet/activity/perday.php #30357
- [x] ./projet/activity/perweek.php #30357
- [x] ./projet/activity/permonth.php #30357
- [x] ./projet/index.php #30357
- [x] ./projet/note.php #30357
- [ ] ./projet/document.php
- [x] ./projet/stats/index.php #30357
- [ ] ./projet/admin/project_extrafields.php
- [x] ./projet/admin/website.php  #30357
- [x] ./projet/admin/project_task_extrafields.php  #30357
- [x] ./projet/admin/project.php  #30357
- [x] ./projet/tasks/task.php
- [x] ./projet/tasks/contact.php #30357
- [x] ./projet/tasks/note.php
- [x] ./projet/tasks/document.php
- [x] ./projet/tasks/time.php
- [x] ./projet/tasks/stats/index.php
- [x] ./projet/tasks/list.php
- [x] ./projet/tasks/comment.php #30357
- [x] ./projet/ganttview.php #30357
- [x] ./projet/agenda.php #30357
- [x] ./projet/list.php #30357
- [x] ./projet/card.php #30357
- [x] ./projet/tasks.php #30357
- [x] ./projet/comment.php #30357
- [x] ./projet/admin/project_extrafields.php #30357
- [x] ./projet/contact.php #30357
- [x] ./projet/document.php #30357
- [x] ./projet/messaging.php #30357

- [ ] **Module expedition**
- [ ] ./expedition/contact.php
- [ ] ./expedition/index.php
- [ ] ./expedition/note.php
- [ ] ./expedition/document.php
- [ ] ./expedition/stats/month.php
- [ ] ./expedition/stats/index.php
- [ ] ./expedition/dispatch.php
- [ ] ./expedition/list.php
- [ ] ./expedition/card.php
- [ ] ./expedition/shipment.php

- [ ] **Module modulebuilder** ** BE CARFULL OF MODULE TEMPLATE**
- [ ] ./modulebuilder/index.php
- [ ] ./modulebuilder/admin/setup.php
- [x] ./modulebuilder/template/myobject_agenda.php #27146
- [x] ./modulebuilder/template/myobject_list.php #27146
- [x] ./modulebuilder/template/myobject_note.php #27146
- [x] ./modulebuilder/template/mymoduleindex.php #27146
- [x] ./modulebuilder/template/myobject_card.php #27146
- [x] ./modulebuilder/template/admin/about.php #27146
- [x] ./modulebuilder/template/admin/myobject_extrafields.php #27146
- [x] ./modulebuilder/template/admin/setup.php #27146
- [x] ./modulebuilder/template/myobject_document.php #27146
- [x] ./modulebuilder/template/myobject_contact.php #27146

- [ ] **Module zapier**
- [ ] ./zapier/admin/about.php
- [ ] ./zapier/admin/setup.php

- [ ] **Module externalsite**
- [ ] ./externalsite/frames.php
- [ ] ./externalsite/frames.php
- [ ] ./externalsite/frames.php
- [x] ./externalsite/admin/index.php
- [ ] ./collab/index.php

- [ ] **Module bookcal**
- [ ] ./bookcal/availabilities_document.php
- [ ] ./bookcal/availabilities_agenda.php
- [ ] ./bookcal/availabilities_list.php
- [ ] ./bookcal/availabilities_note.php
- [ ] ./bookcal/admin/setup.php
- [ ] ./bookcal/admin/booking_extrafields.php
- [ ] ./bookcal/admin/availabilities_extrafields.php
- [ ] ./bookcal/booking_list.php
- [ ] ./bookcal/booking_card.php
- [ ] ./bookcal/availabilities_contact.php
- [ ] ./bookcal/bookcalindex.php
- [ ] ./bookcal/booking_agenda.php
- [ ] ./bookcal/booking_document.php
- [ ] ./bookcal/booking_note.php
- [ ] ./bookcal/availabilities_card.php
- [ ] ./bookcal/booking_contact.php

- [ ] **Module bom**
- [x] ./bom/bom_agenda.php
- [x] ./bom/bom_note.php
- [x] ./bom/bom_card.php
- [x] ./bom/bom_document.php
- [ ] ./bom/bom_list.php
- [x] ./bom/bom_net_needs.php

- [ ] **Module intracommreport**
- [ ] ./intracommreport/admin/intracommreport.php
- [ ] ./intracommreport/list.php
- [ ] ./intracommreport/card.php

- [ ] **Module asterisk**
- [ ] ./asterisk/wrapper.php
- [ ] ./asterisk/wrapper.php

- [ ] **Module reception**
- [ ] ./reception/contact.php
- [ ] ./reception/index.php
- [ ] ./reception/note.php
- [ ] ./reception/document.php
- [ ] ./reception/stats/month.php
- [ ] ./reception/stats/index.php
- [ ] ./reception/dispatch.php
- [ ] ./reception/list.php
- [ ] ./reception/card.php

- [ ] **Module bookmarks**
- [ ] ./bookmarks/admin/bookmark.php
- [ ] ./bookmarks/list.php
- [ ] ./bookmarks/card.php

- [ ] **Module printing**
- [ ] ./printing/index.php
- [ ] ./printing/admin/printing.php

- [ ] **Module mrp** #30373
- [x] ./mrp/mo_note.php
- [x] ./mrp/index.php
- [x] ./mrp/mo_card.php
- [x] ./mrp/mo_movements.php
- [x] ./mrp/mo_agenda.php
- [x] ./mrp/mo_production.php
- [x] ./mrp/mo_list.php
- [x] ./mrp/mo_document.php

- [ ] **Admin pages**
- [ ] ./admin/supplier_order.php
- [ ] ./admin/stocktransfer.php
- [ ] ./admin/modules.php
- [x] ./admin/dict.php
- [x] ./admin/debugbar.php
- [x] ./admin/ecm_files_extrafields.php
- [ ] ./admin/commande.php
- [ ] ./admin/user.php
- [x] ./admin/ecm_directories_extrafields.php
- [x] ./admin/delivery.php
- [x] ./admin/mailing.php
- [ ] ./admin/multicurrency.php
- [ ] ./admin/resource_extrafields.php
- [x] ./admin/bank.php
- [x] ./admin/mails_ingoing.php
- [ ] ./admin/menus.php
- [x] ./admin/bank_extrafields.php
- [x] ./admin/bomline_extrafields.php
- [ ] ./admin/facture_situation.php
- [x] ./admin/agenda_xcal.php
- [x] ./admin/fichinter.php
- [ ] ./admin/index.php
- [x] ./admin/limits.php
- [x] ./admin/ldap_contacts.php
- [ ] ./admin/website_options.php
- [x] ./admin/ecm.php
- [x] ./admin/accountant.php
- [ ] ./admin/spip.php
- [x] ./admin/mailman.php
- [ ] ./admin/website.php
- [x] ./admin/import.php
- [ ] ./admin/openinghours.php
- [ ] ./admin/triggers.php
- [ ] ./admin/stock.php
- [ ] ./admin/syslog.php
- [ ] ./admin/order_extrafields.php
- [x] ./admin/bom_extrafields.php
- [ ] ./admin/oauthlogintokens.php
- [ ] ./admin/mails_ticket.php
- [x] ./admin/boxes.php
- [x] ./admin/agenda_extrafields.php
- [ ] ./admin/supplierorderdet_extrafields.php
- [ ] ./admin/supplier_invoice.php
- [x] ./admin/eventorganization.php
- [ ] ./admin/mrp.php
- [ ] ./admin/modulehelp.php
- [ ] ./admin/taxes.php
- [ ] ./admin/pdf_other.php
- [ ] ./admin/security_file.php
- [ ] ./admin/prelevement.php
- [ ] ./admin/menus/index.php
- [ ] ./admin/menus/edit.php
- [x] ./admin/knowledgemanagement.php
- [ ] ./admin/ticket.php
- [x] ./admin/expensereport_ik.php
- [ ] ./admin/commande_fournisseur_dispatch_extrafields.php
- [ ] ./admin/security.php
- [x] ./admin/loan.php
- [ ] ./admin/proxy.php
- [x] ./admin/hrm.php
- [x] ./admin/accounting.php
- [ ] ./admin/resource.php
- [ ] ./admin/workflow.php
- [ ] ./admin/mrp_extrafields.php
- [ ] ./admin/perms.php
- [x] ./admin/export.php
- [x] ./admin/clicktodial.php
- [x] ./admin/expensereport_extrafields.php
- [x] ./admin/deliverydet_extrafields.php
- [x] ./admin/dav.php
- [ ] ./admin/notification.php
- [ ] ./admin/translation.php
- [x] ./admin/bom.php
- [x] ./admin/emailcollector_list.php
- [x] ./admin/knowledgerecord_extrafields.php
- [x] ./admin/chequereceipts.php
- [ ] ./admin/orderdet_extrafields.php
- [x] ./admin/holiday.php
- [x] ./admin/ldap_members_types.php
- [x] ./admin/fckeditor.php
- [ ] ./admin/ticket_public.php
- [x] ./admin/expensereport_rules.php
- [ ] ./admin/pdf.php
- [ ] ./admin/receiptprinter.php
- [ ] ./admin/webhook.php
- [x] ./admin/mails_emailing.php
- [x] ./admin/events.php
- [ ] ./admin/mails_templates.php
- [x] ./admin/company_socialnetworks.php
- [x] ./admin/ldap_groups.php
- [x] ./admin/ihm.php
- [x] ./admin/compta.php
- [x] ./admin/agenda_reminder.php

- [ ] **Admin ecm**
- [ ] ./ecm/file_note.php
- [ ] ./ecm/file_card.php
- [ ] ./ecm/index.php
- [ ] ./ecm/search.php
- [ ] ./ecm/index_auto.php
- [ ] ./ecm/index_medias.php
- [ ] ./ecm/dir_add_card.php
- [ ] ./ecm/dir_card.php

**Comment by atm-lena** [comment]
@atm-john I take care of the “product” part

**Comment by EchoLoGeek** [comment]
@atm-john I did "BOM" and "partnership" #29875

**Comment by john-botella** [comment]
I will deal with supplier_proposal

**Comment by atm-lena** [comment]
@atm-john I take care of the “user” part

**Comment by EchoLoGeek** [comment]
@atm-john I take care of the "ticket" part

**Comment by atm-lena** [comment]
I'm working on "admin" part 🤓

**Comment by EchoLoGeek** [comment]
@atm-john "ticket" and "resource" are done

**Comment by EchoLoGeek** [comment]
@atm-john Working on "reception"

**Comment by atm-lena** [comment]
@atm-john bookmark & barcode done

**Comment by atm-lena** [comment]
@atm-john export & commande part done

**Comment by atm-lena** [comment]
@atm-john oexport & takepos part done (except invoice.php and phone.php, not necessary)

**Comment by atm-lena** [comment]
@atm-john webhook & webservice & workstation part done

**Comment by EchoLoGeek** [comment]
@atm-john I take care of the "accountancy" part

**Comment by aspangaro** [comment]
@atm-john I finish "accountancy" part that @EchoLoGeek had begun

**Comment by d3v2a** [comment]
Has anyone tested #29969

**Comment by EchoLoGeek** [comment]
@atm-john projects done

**Comment by john-botella** [comment]
List updated @EchoLoGeek @aspangaro

**Comment by atm-lena** [comment]
I take care of the “ficheinter” and "fourn_facture" part
