### ISSUE TITLE
Install Dolibarr from the CLI

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#4674]
# Feature Request

Support installing Dolibarr from the CLI.
## Use case

From cloud providers to automated testing, instantiating Dolibarr from the CLI would be a huge time saver.
## Suggested implementation

Leverage existing install scripts so we don't end up with two separate install processes.

Just as the upgrade is already supported by running something like:

``` sh
cd htdocs/install/
php upgrade.php 3.8.0 3.9.0
php upgrade2.php 3.8.0 3.9.0
php step5.php
```

Also make use of the forced install feature to preset install configuration.
## Tasks
- [X] Enhance forced install process #4673 
- [x] Make sure install scripts run smoothly from CLI
- [ ] Allow them to run from the CLI even with the web interface locked by the install.lock file
- [ ] Make them return sensible status codes
- [ ] Provide a single script that combines all the usual steps
- [ ] Use said script to test install with CI (Travis)
- [ ] Bonus: allow passing settings on the command line rather than with the forced install configuration file

**Comment by elarifr** [comment]
you can try the test i made for dolibarr online upload from github and install :)
not really CLI but a simple php script that can upload from github any tag version and extract htdocs folder at the right place
as it is using php to extract, file owner is apache not the user running command 
http://www.dolibarr.fr/forum/511-creation-dun-nouveau-module/54363-nouveau-module-extrabackup-sauve-docs-htdocs#69001

**Comment by rdoursenaud** [comment]
Thanks @elarifr. Nice idea but this does not fit my use case.
I already use git to manage my production but I need to be able to start new ready-to-go instances for my customers in the blink of an eye ;)
This is also needed to properly test the install process with various configurations (Apache, Nginx, MariaDB, PostgreSQL, various PHP versions…) on our CI. I'm kinda bothered that this crucial step is not tested automatically at the moment.

**Comment by gnovaro** [comment]
I suggest to use composer for that. make a new php script like doli-cli.php or and can accept parameters like task:action 
For example php doli-cli.php core:upgrade

**Comment by scith** [comment]
Hello, I managed to automate install with CURL. I know it's not as pretty as a CLI install but it does the job:
https://github.com/YunoHost-Apps/dolibarr_ynh/blob/efc42505f4a5db96030cd0f725d2b1f190a233bf/scripts/install#L96-L101

You need a forced install conf: https://github.com/YunoHost-Apps/dolibarr_ynh/blob/efc42505f4a5db96030cd0f725d2b1f190a233bf/sources/install.forced.php in htdocs/install/install.forced.php

Cheers

**Comment by vipera7** [comment]
Hey @scith
I would like to ask you how do you manage to install older version with curl ? For example the version 2.5.0
